click_on_sign_in="xpath=/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.widget.LinearLayout/android.view.ViewGroup/androidx.viewpager.widget.ViewPager/androidx.recyclerview.widget.RecyclerView/androidx.compose.ui.platform.ComposeView/android.view.View/android.view.View[2]/android.widget.Button"
click_on_email_field="id=com.booking:id/identity_landing_social_button"
email_field="id=com.booking:id/identity_text_input_edit_text "
email_value="namra@gmail.com"
continue_button="id=com.booking:id/identity_landing_social_button"
pass_field="id=com.booking:id/identity_text_input_edit_text"
pass_value="Testing@123"
Sign_in="id=com.booking:id/identity_landing_social_button"
designation="xpath=//android.widget.Button[@content-desc='Enter your destination']"
country_enter_field="id=com.booking:id/facet_with_bui_free_search_booking_header_toolbar_content"
country_name="Thailand"
select_city_from_drop_down="id=com.booking:id/view_disambiguation_destination_title"
date_picker="id=com.booking:id/facet_date_picker_confirm"
search="xpath=//android.view.View[@content-desc='Accommodation search box']/android.view.View/android.widget.Button"
