username= "id:user-name"
username_value="standard_user"
password = "id:password"
password_value ="secret_sauce"
sign_in= "id:login-button"
search_item_key="xpath://div[normalize-space()='Test.allTheThings() T-Shirt (Red)']"
search_value="Test.allTheThings() T-Shirt (Red)"
description="This classic Sauce Labs t-shirt is perfect to wear when cozying up to your keyboard to automate a few tests. Super-soft and comfy ringspun combed cotton."
url="https://www.saucedemo.com/inventory.html"
browser="chrome"
add_to_cart="id:add-to-cart-test.allthethings()-t-shirt-(red)"
click_on_add_to_cart_icon="xpath://a[@class='shopping_cart_link']"
click_on_check_out_button="xpath://button[@id='checkout']"
first_name="id:first-name"
fname="Namra"
last_name="id:last-name"
Lname="Kanwal"
postal_code="id:postal-code"
pcode="123445"
click_on_continue="id:continue"
checkout="xpath://button[@id='finish']"
Thankyou_message="Thank you for your order!Your order has been dispatched, and will arrive just as fast as the pony can get there!"