username= "//input[@name='username']"
username_value="Admin"
password = "//input[@name='password']"
password_value ="admin123"
sign_in= "xpath://button[@type='submit']"
url="https://opensource-demo.orangehrmlive.com/"
url2="https://demoqa.com/"
browser_chrome="chrome"
browser_firefox="firefox"
Alert_widget="xpath://*[@id='app']/div/div/div[2]/div/div[3]"
Alert_menu="xpath://*[@id='app']/div/div/div/div[1]/div/div/div[3]/span/div/div[1]"
Alert_button="xpath:/html/body/div[2]/div/div/div/div[1]/div/div/div[3]/div/ul/li[2]/span"
Click_me="xpath:/html/body/div[2]/div/div/div/div[2]/div[2]/div[1]/div[2]/button"
Widgets="xpath=(//div)[28]"
Click_on_date_picker="xpath:/html/body/div[2]/div/div/div/div[1]/div/div/div[4]/div/ul/li[3]/span"
Select_Date_field="xpath://input[@id='datePickerMonthYearInput']"
Select_month="xpath://*[@id='datePickerMonthYear']/div[2]/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/select/option[11]"
Click_month="xpath:/html/body/div[2]/div/div/div/div[2]/div[2]/div[1]/div[2]/div[2]/div[2]/div/div/div[2]/div[1]/div[1]"
Click_on_year="xpath:/html/body/div[2]/div/div/div/div[2]/div[2]/div[1]/div[2]/div[2]/div[2]/div/div/div[2]/div[1]/div[2]/div[2]/select"
Select_year="xpath://*[@id='datePickerMonthYear']/div[2]/div[2]/div/div/div[2]/div[1]/div[2]/div[2]/select/option[94]"
Click_on_date="xpath://*[@id='datePickerMonthYear']/div[2]/div[2]/div/div/div[2]/div[2]/div[2]/div[3]"
alphabet_list="xpath://*[@id='demo-tabpane-list']"
interaction_widget="xpath:(//div[@class='card-up'])[5]"
click_on_sortable="xpath:/html/body/div[2]/div/div/div/div[1]/div/div/div[5]/div/ul/li[1]"
Click_grid="xpath://*[@id='demo-tab-grid']"
fifth_element="xpath:/html/body/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div/div/div[5]"
nineth_element="xpath:/html/body/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div/div/div[9]"
user_profile_checkin_key ="xpath:/html[1]/body[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/p[1]"
user_profile_checkin_value="Time at work"
my_action_key="xpath://p[normalize-space()='My Actions']"
my_action_value="My Actions"
quick_launch_key="xpath://p[normalize-space()='Quick Launch']"
quick_launch_value="Quick Launch"
click_on_recruitment="xpath://li[5][@class='oxd-main-menu-item-wrapper']"
click_on_vacancies_tab="xpath://a[normalize-space()='Vacancies']"
select_job_title="xpath://html/body/div[1]/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[1]/div/div[2]/div/div/div[2]/i"
click_on_desired_job_title="xpath:/html[1]/body[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]"
click_on_search_button="//button[@class='oxd-button oxd-button--medium oxd-button--secondary orangehrm-left-space']"
click_on_directory= "xpath://html/body/div[1]/div[1]/div[1]/aside/nav/div[2]/ul/li[9]/a"
click_on_employee_designation_field="xpath://*[@id='app']/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[2]/div/div[2]/div/div/div[2]/i "
click_on_designation_name="xpath://<span>[2]"
click_book_store="xpath://*[@id='app']/div/div/div[2]/div/div[6]/div/div[1]"
username_of_user="xpath://*[@id='userName']"
input_username="NamraKanwal"
pass_of_user="xpath://*[@id='password']"
input_pass="testing@123"
login_button="xpath://*[@id='login']"
list_of_books="xpath://*[@id='app']/div/div/div/div[2]/div[2]/div[2]/div[1]"
